# Setup
title:               sara m. b. simon
tagline:             ''
description:         ''
url:                 https://smbsimon.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Sara Simon
  url:               https://twitter.com/sarambsimon
  email:             smbsimon@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
